task: detection

num_classes: 18
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
#     img_folder: /home/nas/Workspace/Sophia/CVPDL/Original/train/images
#     ann_file: /home/nas/Workspace/Sophia/CVPDL/Original/train_RT.json
    img_folder: /home/nas/Workspace/Sophia/CVPDL/custom/train2017
    ann_file: /home/nas/Workspace/Sophia/CVPDL/custom/annotations/train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 4
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/nas/Workspace/Sophia/CVPDL/custom/val2017
    ann_file: /home/nas/Workspace/Sophia/CVPDL/custom/annotations/val.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 4
  num_workers: 4
  drop_last: False